### ISSUE TITLE
How to use the Rclone browser with the RCLONE installed on QNAP?

### ISSUE THREAD

**Issue by gelsas** [romancin/rclonebrowser-docker#1]
How to use the Rclone browser with the RCLONE installed on QNAP?

I just installed the rclone browser in the Container Station of my QNAP and it is running. 

How do I make it work with the Rclone which is installed on my qnap already ?

I want to backup my whole NAS to google drive and would like this gui because I am not so good with command line.

Sorry for this stupid questions but I am not sure what I need to do now to make it work.

**Comment by romancin** [comment]
Why use the Rclone on the QNAP? Map your entire /share directory to the container and use the embedded rclone on it.

**Comment by gelsas** [comment]
edit got it so far, now I only need to figure out on how to set it up to continuously backup my NAS
