### ISSUE TITLE
Noabody fork not available anymore in github

### ISSUE THREAD

**Issue by caspertone2003** [romancin/rclonebrowser-docker#13]
Perhaps you should switch to
https://github.com/kapitainsky/RcloneBrowser/releases

**Comment by romancin** [comment]
Done. Thank you for your advice :)

**Comment by caspertone2003** [comment]
my pleasure, thanks for the docker image!

**Comment by caspertone2003** [comment]
by the way, in the main page you should also update the reference to the fork...
