### ISSUE TITLE
Cron daemon doesn't run after boot

### ISSUE THREAD

**Issue by cferrey** [romancin/rclonebrowser-docker#15]
Per the title, crond does not automatically start up after boot.  Would be great to get this working, as it would help to automate recurring sync jobs.  I have tried numerous workarounds via docker-compose tweaks but have not had any success via this route, so I imagine it will necessitate changes to the base Dockerfile.  Could this be implemented?  Thanks much!

**Comment by qy2009** [comment]
I would love this as well. I have a few regular recurrent jobs...and I don't know how to do it...

**Comment by cferrey** [comment]
@qy2009 Found a solution for this -- you need only add the following to your docker-compose block for this container:

command: sh -c "crond && /init"

**Comment by glassman81** [comment]
How would you accomplish this using the docker run command?
