### ISSUE TITLE
Rclone Browser 1.7.0 released

### ISSUE THREAD

**Issue by Lonli-Lokli** [romancin/rclonebrowser-docker#18]
Could you please update to the latest one?

**Comment by romancin** [comment]
I am trying to do this since a couple of days, but something has changed for XQt applications and it is not working for now. I need time to troubleshoot the new image correctly. Sorry!

**Comment by Lonli-Lokli** [comment]
@romancin can you include some changes to etc/fuse.conf? 
I faced an issue with this image as it was not possible to use rclone with --allow-other as got an error
option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf

**Comment by romancin** [comment]
Updated to 1.8.0
