### ISSUE TITLE
Please update to latest Rclone Browser 1.8.0

### ISSUE THREAD

**Issue by xianx** [romancin/rclonebrowser-docker#20]
Hello,

Its a nice project. Please update to latest Rclone Browser 1.8.0

Thanks.

**Comment by romancin** [comment]
As stated on issue #18 , the new version doesn't work for the moment. It only runs fine for me on first run, when container is rebooted, rclonebrowser doesn't start again until I delete its config file. Sorry, but I tried a lot of things and it doesn't work for the moment. Closing this as it is duplicated.
