### ISSUE TITLE
Latest version of rclone is not working

### ISSUE THREAD

**Issue by xianx** [romancin/rclonebrowser-docker#21]
I have build docker image from source but the not working. Also tried develop-v2.0.0 and develop-v2.0 from dockerhub https://hub.docker.com/r/romancin/rclonebrowser but not working. Any fix?

**Comment by romancin** [comment]
As stated on issue #18 , the new version doesn't work for the moment. It only runs fine for me on first run, when container is rebooted, rclonebrowser doesn't start again until I delete its config file. Sorry, but I tried a lot of things and it doesn't work for the moment. Closing this as it is duplicated.

**Comment by xianx** [comment]
According to https://github.com/kapitainsky/RcloneBrowser/issues/97 has the problem be solved? Can we get the fixed docker image on docker hub?

**Comment by romancin** [comment]
I have just built develop version. Try and tell us If It world fine for you :)

**Comment by xianx** [comment]
1. what docker image should I try latest or develop-v3.0.0? 

2. why there are so many duplicate docker images like develop-v3.0.0, v3.0.0, v3.0, develop-v3.0, develop-v3, v3, develop, v3.0?

**Comment by romancin** [comment]
I had time to test It and merged to master, so you can use latest.

**Comment by xianx** [comment]
rclone version and other info not showing https://techtun.es/M62Rbi

**Comment by xianx** [comment]
why there are so many duplicate docker images like develop-v3.0.0, v3.0.0, v3.0, develop-v3.0, develop-v3, v3, develop, v3.0?
