### ISSUE TITLE
Small info correction

### ISSUE THREAD

**Issue by kapitainsky** [romancin/rclonebrowser-docker#24]
On

https://hub.docker.com/r/romancin/rclonebrowser/

you have not changed yet all info. Tiny correction:)

<img width="770" alt="Screenshot 2020-03-24 at 19 18 31" src="https://user-images.githubusercontent.com/15635386/77467751-7203d600-6e04-11ea-8bfa-86930e403857.png">

**Comment by romancin** [comment]
Oh, sorry! Fixed on #25
