### ISSUE TITLE
Chinese does not support display

### ISSUE THREAD

**Issue by ironstress** [romancin/rclonebrowser-docker#31]
![屏幕截图 2021-04-05 091756](https://user-images.githubusercontent.com/11043549/113527436-1f045780-95f0-11eb-879c-21e5e39f2ed7.jpg)
![屏幕截图 2021-04-05 091945](https://user-images.githubusercontent.com/11043549/113527437-20ce1b00-95f0-11eb-9d78-6507ac038c89.jpg)

**Comment by eritpchy** [comment]
Use env var ENABLE_CJK_FONT

**Comment by lingfengcoder** [comment]
will,its does not work.Here is the new issue: 10-cjk-font.sh: ERROR: FDB format error (line 4845)

**Comment by lingfengcoder** [comment]
I saw this,and try to upgrade the apk-tool to apk-tools-2.10.8-r1.
Finally,It works!!!
![image](https://github.com/romancin/rclonebrowser-docker/assets/30565113/9efd4753-034a-456c-ac4e-899670e56c43)
![image](https://github.com/romancin/rclonebrowser-docker/assets/30565113/d3677881-566b-4b00-99e8-ba27a792fe4c)
