### ISSUE TITLE
RClone at v.1.53.0 - Update always to latest version

### ISSUE THREAD

**Issue by pchristod** [romancin/rclonebrowser-docker#35]
Hi,

I'm not really sure why because as far as I can see it the link in the Dockerfile `http://downloads.rclone.org/rclone-${RCLONE_VERSION}-linux-${ARCH}.zip` should always point to the current version of rclone as tested via Browser. Still however RcloneBrowser seems to run with 1.53.0 currently. Is there any way to update always to the latest version?
1.53.0 seems pretty old and a lot if things have changed and serious issues have been fixed, e.g. generating weak passwords https://github.com/rclone/rclone/issues/4783.

![Unbenannt](https://user-images.githubusercontent.com/17931739/151134023-a1b3c6b0-af8d-43a4-af9f-f263a9249df2.JPG)

Thanks for any input!

**Comment by DrMxrcy** [comment]
No clue why its not working, I cloned the repo and Just fixed it myself

**Comment by pchristod** [comment]
@DrMxrcy What did you have to change exactly?

**Comment by DrMxrcy** [comment]
Heres my DockerFile, I just changed how the download was parsed.

[PasteBin Link](https://pastebin.com/n4Tarij9)

And heres my screenshot of it working after my build

<img width="1721" alt="Screen Shot 2022-05-11 at 1 14 29 AM" src="https://user-images.githubusercontent.com/58747968/167774133-45ddbccb-1247-4f1b-ab10-4ed83e0c26af.png">

**Comment by DrMxrcy** [comment]
@pchristod Hopefully that helps!

**Comment by pchristod** [comment]
@DrMxrcy Thanks, highly appreciated your help!

**Comment by DrMxrcy** [comment]
@pchristod No problem! Just kept my img private because of docker hub limits. Good luck!

**Comment by pchristod** [comment]
Just letting you know that the solution works 😁 
So anyone with the same problem can use this workaround.

**Comment by DrMxrcy** [comment]
Yup, I have been using it well!

**Comment by DrMxrcy** [comment]
I made a fork and published the docker file with github, for easy use https://github.com/DrMxrcy/rclonebrowser-docker

**Comment by deejayexe** [comment]
> Heres my DockerFile, I just changed how the download was parsed.
> 
> [PasteBin Link](https://pastebin.com/n4Tarij9)
> 
> And heres my screenshot of it working after my build
> 
> <img alt="Screen Shot 2022-05-11 at 1 14 29 AM" width="1721" src="https://user-images.githubusercontent.com/58747968/167774133-45ddbccb-1247-4f1b-ab10-4ed83e0c26af.png">

Hi!
I want to try ur docker image, but can u tell me If u have any bugs with rclone version about empty fields how here -> https://github.com/kapitainsky/RcloneBrowser/issues/198

Thanks for ur time.

**Comment by pchristod** [comment]
Hi,

I'm not @DrMxrcy but I can confirm that this Bug is present with the latest RClone Version. Didn't even notice it before.

**Comment by DrMxrcy** [comment]
Yes it is still present. I haven't had a chance to take a look at it

**Comment by pchristod** [comment]
I will close this Issue as RClone was updated like 20 Days ago. The issue @deejayexe mentioned (missing Stats) is still there but it seems this comes from RcloneBrowser itself and is still an open Issue there https://github.com/kapitainsky/RcloneBrowser/issues/198
