### ISSUE TITLE
Waiting for Authentication Code for Google Drive

### ISSUE THREAD

**Issue by qy2009** [romancin/rclonebrowser-docker#5]
Hi,

I just set it up on docker...and try to add google drive sync..how can I get the authentication code ? 

it said http://127.0.0.1:xxx/auth

I tried to use my NAS IP ...but not working...thanks

**Comment by rapejim** [comment]
> Hi,
> 
> I just set it up on docker...and try to add google drive sync..how can I get the authentication code ?
> 
> it said http://127.0.0.1:xxx/auth
> 
> I tried to use my NAS IP ...but not working...thanks

Try answering "n" in the next question:
![image](https://user-images.githubusercontent.com/7972545/59162904-4aec4a00-8af9-11e9-8a1c-750f8038098b.png)

Then the application will give you a code that is not based on ip 127.0.0.1 and that you can use in another tab of the web browser.

Anyway, if you can't do it this way... I downloaded RcloneBrowser for desktop and configured it. Then I copied the file "rclone.conf" and copied it to the ".../config/xdg/config/rclone/" folder on the host (on my Synology).
![image](https://user-images.githubusercontent.com/7972545/59162954-1af17680-8afa-11e9-878f-ea9ad8547588.png)

**Comment by qy2009** [comment]
got it. thanks so much :)
