### ISSUE TITLE
RCloneBrowser fork used

### ISSUE THREAD

**Issue by caspertone2003** [romancin/rclonebrowser-docker#9]
Hi,
There are, besides mmozeiko original version - https://github.com/mmozeiko/RcloneBrowser

Three other forks: 
https://github.com/kapitainsky/RcloneBrowser/releases (most up to date)
https://github.com/DinCahill/RcloneBrowser
https://github.com/AndyIbanez/RcloneBrowser

Which version did you embed in this docker image?

Or perhaps do you use another software?

On the other hand, if you used one of the above, perhaps documentation should reflect that fact...

TIA

**Comment by rapejim** [comment]
It's in Readme, 😜 


>This is a completely funcional Docker image with RClone Browser (noabody fork).


"_noabody fork_"

Edit:
https://github.com/noabody/RcloneBrowser
(it's a fork, from DinCahill fork)

**Comment by rapejim** [comment]
Maybe the _kapitainsky_ fork is a good option too.

**Comment by caspertone2003** [comment]
> 
> 
> It's in Readme, 😜
> 
> > This is a completely funcional Docker image with RClone Browser (noabody fork).
> 
> "_noabody fork_"
> 
my fault... skept the end of that line... 

I was no aware of the availability of noabody fork... at the end it is a pity so many disparate efforts...
Will point to noabody and to kapitainsky to each other....

Thanks!
